### PR TITLE
Update vdpa-deploymnet to match currents state

### PR DESCRIPTION
**Pull request by amorenoz**
Hi @Billy99, this is my branch where I've cleaned up most of the previous deployment files and added those that match the current design.
Currently done:
- Rewritten Readme.md
- Cleaned makefile to just build Device Plugin, and CNI. Point to the current (personal) vdpa branches
- Create a "devel" image: just for experimentation and development.

Current TODO list:
- Integrate the dpdk-centos image  and the rest of the examples with app-netutils
- Integrate dpdk-devel with app-netutils
- Install govdpa tools for vdpa inspection
- Install the right version of Multus (right now the Makefile won't install any version and we require one in which the DeviceInfo spec is supported)
- Add a simple virtio-net performance testing deployment (and maybe compare it with a kernel-based solution such as macvlan)
- Point to official repos once the code gets merged

Since there is still a log to do list and this is already a long PR, I'm wondering what's the best way to do it. Should we merge this and add Issues to reflect the TODOs?

### CODE REVIEW

**Comment by Billy99** [comment]
@amorenoz This is a development repo. So if it helps you manage or if you want to share the code with others, feel free to merge. I don't think it matters which approach you take.

**Comment by amorenoz** [comment]
OK. In that case, I'd say we merge this and use it to share the status of the PRs that we currently have open on Device Plugin and CNI

**Comment by Billy99** [comment]
> OK. In that case, I'd say we merge this and use it to share the status of the PRs that we currently have open on Device Plugin and CNI

Do you have permissions or do you need me to do it? If me, are you ready?

**Comment by amorenoz** [comment]
I do :)

**Pull request merged**
